import {
  baklavaImg,
  baklavaThumb,
  brownieImg,
  brownieThumb,
  cakeImg,
  cakeThumb,
  cremeBruleeImg,
  cremeBruleeThumb,
  macaronImg,
  macaronThumb,
  pannaCottaImg,
  pannaCottaThumb,
  pieImg,
  pieThumb,
  tiramisuImg,
  tiramisuThumb,
  waffleImg,
  waffleThumb,
} from '../assets'

const initialProducts = [
  {
    id: 1,
    name: 'Waffle with Berries',
    category: 'Waffle',
    img: waffleImg,
    thumb: waffleThumb,
    price: 6.5,
    count: 0,
  },
  {
    id: 2,
    name: 'Vanilla Bean Crème Brûlée',
    category: 'Crème Brûlée',
    img: cremeBruleeImg,
    thumb: cremeBruleeThumb,
    price: 7.0,
    count: 0,
  },
  {
    id: 3,
    name: 'Macaron Mix of Five',
    category: 'Macaron',
    img: macaronImg,
    thumb: macaronThumb,
    price: 8.0,
    count: 0,
  },
  {
    id: 4,
    name: 'Classic Tiramisu',
    category: 'Tiramisu',
    img: tiramisuImg,
    thumb: tiramisuThumb,
    price: 5.5,
    count: 0,
  },
  {
    id: 5,
    name: 'Pistachio Baklava',
    category: 'Baklava',
    img: baklavaImg,
    thumb: baklavaThumb,
    price: 4.0,
    count: 0,
  },
  {
    id: 6,
    name: 'Lemon Meringue Pie',
    category: 'Pie',
    img: pieImg,
    thumb: pieThumb,
    price: 5.0,
    count: 0,
  },
  {
    id: 7,
    name: 'Red Velvet Cake',
    category: 'Cake',
    img: cakeImg,
    thumb: cakeThumb,
    price: 4.5,
    count: 0,
  },
  {
    id: 8,
    name: 'Salted Caramel Brownie',
    category: 'Brownie',
    img: brownieImg,
    thumb: brownieThumb,
    price: 4.5,
    count: 0,
  },
  {
    id: 9,
    name: 'Vanilla Panna Cotta',
    category: 'Panna Cotta',
    img: pannaCottaImg,
    thumb: pannaCottaThumb,
    price: 6.5,
    count: 0,
  },
]

export default initialProducts
